export type Severity='info'|'warning'|'high'|'critical';
export type RiskLevel='low'|'medium'|'high'|'critical';
export type RiskFactor={rule_id:string;weight:number;evidence:Record<string,unknown>};
export type ProviderHealthMetrics={operations_total:number;operations_completed:number;operations_failed:number;operations_unknown:number;failure_rate:number;unknown_rate:number;consecutive_failures:number;last_success_at:string|null;last_failure_at:string|null;baseline_failure_rate:number|null;baseline_status:'AVAILABLE'|'INSUFFICIENT_BASELINE'};
export const GUARD_THRESHOLDS={minimumSample:10,degradedFailureRate:.10,criticalFailureRate:.25,degradedUnknownRate:.10,criticalUnknownRate:.25,consecutiveFailures:3,waveSize:5,waveMinutes:10,alertCooldownMs:30*60_000}as const;
export function providerHealthStatus(m:ProviderHealthMetrics):'healthy'|'degraded'|'critical'|'unknown'{if(!m.operations_total)return'unknown';if(m.operations_total>=GUARD_THRESHOLDS.minimumSample&&(m.failure_rate>=GUARD_THRESHOLDS.criticalFailureRate||m.unknown_rate>=GUARD_THRESHOLDS.criticalUnknownRate))return'critical';if((m.operations_total>=GUARD_THRESHOLDS.minimumSample&&(m.failure_rate>=GUARD_THRESHOLDS.degradedFailureRate||m.unknown_rate>=GUARD_THRESHOLDS.degradedUnknownRate))||m.consecutive_failures>=GUARD_THRESHOLDS.consecutiveFailures)return'degraded';return'healthy'}
export function riskLevel(score:number):RiskLevel{return score>=75?'critical':score>=50?'high':score>=25?'medium':'low'}
export function calculateRisk(factors:RiskFactor[]){const score=Math.max(0,Math.min(100,factors.reduce((n,f)=>n+f.weight,0)));return{score,level:riskLevel(score),factors}}
export type RuleCondition={metric:string;operator:'>='|'>'|'='|'<='|'<';value:number;minimum_sample?:number;window?:'15m'|'1h'|'24h'};
export function evaluateRule(c:RuleCondition,value:number,sample:number){if(c.minimum_sample&&sample<c.minimum_sample)return false;return c.operator==='>='?value>=c.value:c.operator==='>'?value>c.value:c.operator==='='?value===c.value:c.operator==='<='?value<=c.value:value<c.value}
export const complianceReasons=new Set(['fraud','suspected_abuse','platform_policy_block','compliance_review','enforcement']);
export function isComplianceEvent(type:string,data:Record<string,unknown>){return type.includes('compliance')||type.includes('policy_block')||complianceReasons.has(String(data.reason??''))}
export function waveKey(providerId:string,region:string,at:Date){const width=GUARD_THRESHOLDS.waveMinutes*60_000;return`${providerId}:${region}:${Math.floor(at.getTime()/width)}`}
export function selectPlaybook(trigger:string){if(trigger.includes('compliance'))return'COMPLIANCE_REVIEW';if(trigger.includes('reconciliation_required'))return'RECONCILIATION_REQUIRED';if(trigger.includes('unknown'))return'OUTCOME_UNKNOWN';if(trigger.includes('activation'))return'ACTIVATION_FAILURE_WAVE';if(trigger.includes('sim'))return'SIM_FAILURE';return'PROVIDER_OUTAGE'}
export interface GuardExplainer{explain(input:{count:number;subject:string;minutes:number;rate?:number;baseline?:number|null;region?:string}):string}
export class DeterministicGuardExplainer implements GuardExplainer{explain(x:{count:number;subject:string;minutes:number;rate?:number;baseline?:number|null;region?:string}){const rate=x.rate===undefined?'':` A taxa observada é ${(x.rate*100).toFixed(1)}%.`;const baseline=x.baseline==null?' Baseline insuficiente.':` O baseline é ${(x.baseline*100).toFixed(1)}%.`;return`${x.count} ocorrências de ${x.subject} foram detectadas nos últimos ${x.minutes} minutos${x.region?` na região ${x.region}`:''}.${rate}${baseline}`}}
