export type ProviderOperationStatus='completed'|'failed'|'unknown';export type ProviderOperationResult={reference?:string;status:ProviderOperationStatus;error?:string};export type ProviderOperation=ProviderOperationResult;export type ProviderCommand={resourceId:string;operationKey:string;credentials?:Record<string,unknown>};export type ProviderStatusCommand={operationKey:string;providerReference?:string;resourceId:string;credentials?:Record<string,unknown>};export type ProviderCapabilities={activation:boolean;operation_status:boolean;suspend:false;resume:false;terminate:false;usage:false;provisioning:false};export const sandboxCapabilities:ProviderCapabilities={activation:true,operation_status:true,suspend:false,resume:false,terminate:false,usage:false,provisioning:false};
export type ProviderErrorCode='PROVIDER_TIMEOUT'|'PROVIDER_UNAVAILABLE'|'PROVIDER_AUTH_FAILED'|'PROVIDER_RATE_LIMITED'|'PROVIDER_INVALID_REQUEST'|'PROVIDER_CAPABILITY_UNSUPPORTED'|'PROVIDER_OUTCOME_UNKNOWN'|'PROVIDER_NOT_CONFIGURED';
export class ProviderError extends Error{readonly terminal:boolean;constructor(message:string,public readonly code:ProviderErrorCode,public readonly retryable:boolean,public readonly outcomeUnknown=false){super(message);this.terminal=!retryable&&!outcomeUnknown}}
export interface ConnectivityProvider{readonly capabilities:ProviderCapabilities;activate(command:ProviderCommand):Promise<ProviderOperationResult>;getOperationStatus(command:ProviderStatusCommand):Promise<ProviderOperationResult>;getStatus?(resourceId:string):Promise<'available'|'active'|'suspended'>}
export class ProviderRegistry{private adapters=new Map<string,ConnectivityProvider>();register(providerId:string,adapter:ConnectivityProvider){this.adapters.set(providerId,adapter);return this}get(providerId:string){const adapter=this.adapters.get(providerId);if(!adapter)throw new ProviderError(`Provider adapter ${providerId} is not configured`,'PROVIDER_NOT_CONFIGURED',false);return adapter}}
export const asProviderRegistry=(provider:ProviderRegistry|ConnectivityProvider,providerId:string)=>provider instanceof ProviderRegistry?provider:new ProviderRegistry().register(providerId,provider);
export type SandboxMode='success'|'timeout'|'timeout_unknown'|'temporary_failure'|'terminal_failure'|'unknown'|'unknown_then_completed'|'unknown_then_failed'|'permanently_unknown';
export class SandboxProviderStore{operations=new Map<string,ProviderOperationResult>();queries=new Map<string,number>()}
export class SandboxProvider implements ConnectivityProvider{readonly capabilities:ProviderCapabilities;constructor(private mode:SandboxMode='success',private store=new SandboxProviderStore(),capabilities:Partial<ProviderCapabilities>={}){this.capabilities={...sandboxCapabilities,...capabilities}as ProviderCapabilities}async activate(c:ProviderCommand){if(!this.capabilities.activation)throw new ProviderError('Activation capability is unsupported','PROVIDER_CAPABILITY_UNSUPPORTED',false);const old=this.store.operations.get(c.operationKey);if(old)return old;if(this.mode==='timeout')throw new ProviderError('Provider timeout before known side effect','PROVIDER_TIMEOUT',true);if(this.mode==='timeout_unknown')throw new ProviderError('Provider timeout with unknown outcome','PROVIDER_OUTCOME_UNKNOWN',false,true);if(this.mode==='temporary_failure')throw new ProviderError('Provider unavailable','PROVIDER_UNAVAILABLE',true);if(this.mode==='terminal_failure')return{status:'failed' as const,error:'Sandbox terminal activation failure'};if(['unknown','unknown_then_completed','unknown_then_failed','permanently_unknown'].includes(this.mode)){const value={status:'unknown' as const,error:'Provider outcome requires reconciliation'};this.store.operations.set(c.operationKey,value);return value}const value={status:'completed' as const,reference:`sbx_${c.operationKey}`};this.store.operations.set(c.operationKey,value);return value}async getOperationStatus(c:ProviderStatusCommand){if(!this.capabilities.operation_status)throw new ProviderError('Operation status capability is unsupported','PROVIDER_CAPABILITY_UNSUPPORTED',false);const count=(this.store.queries.get(c.operationKey)??0)+1;this.store.queries.set(c.operationKey,count);if(this.mode==='unknown_then_completed'&&count>=1){const value={status:'completed' as const,reference:`sbx_${c.operationKey}`};this.store.operations.set(c.operationKey,value);return value}if(this.mode==='unknown_then_failed'&&count>=1){const value={status:'failed' as const,error:'Reconciled provider failure'};this.store.operations.set(c.operationKey,value);return value}return this.store.operations.get(c.operationKey)??{status:'unknown' as const}}async getStatus(){return'active'as const}}
export async function withProviderTimeout<T>(operation:Promise<T>,ms:number,outcomeUnknown:boolean){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([operation,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new ProviderError('Provider operation timed out',outcomeUnknown?'PROVIDER_OUTCOME_UNKNOWN':'PROVIDER_TIMEOUT',!outcomeUnknown,outcomeUnknown)),ms)})])}finally{if(timer)clearTimeout(timer)}}
