import {randomUUID} from 'node:crypto';
import {and,eq,sql as dsql} from 'drizzle-orm';
import {pathToFileURL} from 'node:url';
import {config} from './config.js';
import {db as defaultDb} from './db.js';
import {assignments,events,incidents,jobs,lines,providerOrders,replacements,webhookDeliveries,webhooks} from './db/schema.js';
import {assertSourceReplaceable,DomainError,retryDelayMs} from './domain.js';
import {ConnectivityProvider,ProviderError,SandboxProvider} from './provider.js';
type Database=typeof defaultDb;
export type ClaimedJob={id:string;organizationId:string;payload:{replacementId:string};attempts:number;lockedBy:string};
const id=(p:string)=>`${p}_${randomUUID().replaceAll('-','')}`;

export async function claimJob(database:Database,workerId:string,now=new Date()):Promise<ClaimedJob|undefined>{const leaseCutoff=new Date(now.getTime()-config.JOB_LEASE_MS);return database.transaction(async tx=>{const rows=await tx.execute(dsql`select id,organization_id,payload,attempts from jobs where type='replacement.execute' and available_at<=${now.toISOString()}::timestamptz and (status='pending' or (status='processing' and locked_at<${leaseCutoff.toISOString()}::timestamptz)) order by available_at,id for update skip locked limit 1`);const row=rows[0] as {id:string;organization_id:string;payload:{replacementId:string};attempts:number}|undefined;if(!row)return;await tx.update(jobs).set({status:'processing',lockedAt:now,lockedBy:workerId,attempts:row.attempts+1}).where(eq(jobs.id,row.id));return{id:row.id,organizationId:row.organization_id,payload:row.payload,attempts:row.attempts+1,lockedBy:workerId};});}

async function reserveTarget(database:Database,replacementId:string){return database.transaction(async tx=>{const[replacement]=await tx.select().from(replacements).where(eq(replacements.id,replacementId)).limit(1);if(!replacement)throw new DomainError('RESOURCE_NOT_FOUND','Replacement not found');if(replacement.status==='completed')return{replacement,alreadyCompleted:true as const,target:undefined};const[source]=await tx.select().from(lines).where(and(eq(lines.organizationId,replacement.organizationId),eq(lines.id,replacement.sourceLineId))).limit(1);if(!source)throw new DomainError('RESOURCE_NOT_FOUND','Source line not found');assertSourceReplaceable(source.status);if(replacement.targetLineId){const[target]=await tx.select().from(lines).where(and(eq(lines.organizationId,replacement.organizationId),eq(lines.id,replacement.targetLineId))).limit(1);if(!target)throw new DomainError('RESOURCE_NOT_FOUND','Reserved target not found');return{replacement,source,target,alreadyCompleted:false as const};}const rows=await tx.execute(dsql`select id from lines where organization_id=${replacement.organizationId} and status='available' and id<>${source.id} and region=${source.region} and sim_type=${source.simType} order by created_at,id for update skip locked limit 1`);const candidate=rows[0] as {id:string}|undefined;if(!candidate)throw new DomainError('NO_ELIGIBLE_RESOURCE','No eligible connectivity resource');const[target]=await tx.update(lines).set({status:'provisioning',reservedByReplacementId:replacement.id,updatedAt:new Date()}).where(and(eq(lines.id,candidate.id),eq(lines.organizationId,replacement.organizationId),eq(lines.status,'available'))).returning();if(!target)throw new DomainError('NO_ELIGIBLE_RESOURCE','Eligible resource was concurrently reserved');await tx.update(replacements).set({status:'processing',targetLineId:target.id}).where(and(eq(replacements.id,replacement.id),eq(replacements.organizationId,replacement.organizationId)));return{replacement:{...replacement,status:'processing' as const,targetLineId:target.id},source,target,alreadyCompleted:false as const};});}

export async function executeReplacement(database:Database,provider:ConnectivityProvider,replacementId:string){const reservation=await reserveTarget(database,replacementId);if(reservation.alreadyCompleted)return;const{replacement,target}=reservation;const operationKey=`${target.providerId}:activate:${replacement.id}`;await database.insert(providerOrders).values({id:id('ord'),organizationId:replacement.organizationId,replacementId:replacement.id,providerId:target.providerId,operation:'activate',operationKey,resourceId:target.id,status:'processing'}).onConflictDoNothing();const[order]=await database.select().from(providerOrders).where(eq(providerOrders.operationKey,operationKey)).limit(1);if(!order)throw new Error('Provider order persistence failed');if(order.status==='completed')return completeReplacement(database,replacement.id);if(order.status==='unknown')throw new DomainError('PROVIDER_OUTCOME_UNKNOWN','Provider outcome requires reconciliation');let operation;try{operation=await provider.activate({resourceId:target.id,operationKey});}catch(error){if(error instanceof ProviderError&&error.outcomeUnknown)await database.update(providerOrders).set({status:'unknown',error:error.message}).where(eq(providerOrders.id,order.id));throw error;}if(operation.status==='unknown'){await database.update(providerOrders).set({status:'unknown',error:operation.error}).where(eq(providerOrders.id,order.id));throw new DomainError('PROVIDER_OUTCOME_UNKNOWN','Provider outcome requires reconciliation');}if(operation.status==='failed'){await database.update(providerOrders).set({status:'failed',error:operation.error,completedAt:new Date()}).where(eq(providerOrders.id,order.id));throw new DomainError('PROVISIONING_FAILED',operation.error??'Provider activation failed');}await database.update(providerOrders).set({status:'completed',providerReference:operation.reference,completedAt:new Date()}).where(eq(providerOrders.id,order.id));await completeReplacement(database,replacement.id);}

async function completeReplacement(database:Database,replacementId:string){await database.transaction(async tx=>{const[replacement]=await tx.select().from(replacements).where(eq(replacements.id,replacementId)).limit(1);if(!replacement||replacement.status==='completed')return;if(!replacement.targetLineId)throw new DomainError('INVALID_STATE_TRANSITION','Replacement has no reserved target');const[source]=await tx.select().from(lines).where(and(eq(lines.organizationId,replacement.organizationId),eq(lines.id,replacement.sourceLineId))).limit(1);const[target]=await tx.select().from(lines).where(and(eq(lines.organizationId,replacement.organizationId),eq(lines.id,replacement.targetLineId))).limit(1);if(!source||!target)throw new DomainError('RESOURCE_NOT_FOUND','Replacement resources not found');assertSourceReplaceable(source.status);if(target.status!=='provisioning'||target.reservedByReplacementId!==replacement.id)throw new DomainError('INVALID_STATE_TRANSITION','Target reservation was lost');const[current]=await tx.select().from(assignments).where(and(eq(assignments.organizationId,replacement.organizationId),eq(assignments.lineId,source.id),dsql`${assignments.endedAt} is null`)).limit(1);await tx.update(lines).set({status:'replaced',reservedByReplacementId:null,updatedAt:new Date()}).where(eq(lines.id,source.id));await tx.update(lines).set({status:'active',reservedByReplacementId:null,updatedAt:new Date()}).where(and(eq(lines.id,target.id),eq(lines.reservedByReplacementId,replacement.id)));if(current){await tx.update(assignments).set({endedAt:new Date()}).where(and(eq(assignments.id,current.id),dsql`${assignments.endedAt} is null`));await tx.insert(assignments).values({id:`asn_${replacement.id}`,organizationId:replacement.organizationId,lineId:target.id,personId:current.personId,deviceId:current.deviceId,costCenter:current.costCenter}).onConflictDoNothing();}if(replacement.incidentId)await tx.update(incidents).set({status:'resolved',resolvedAt:new Date()}).where(and(eq(incidents.organizationId,replacement.organizationId),eq(incidents.id,replacement.incidentId)));await tx.update(replacements).set({status:'completed',failureCode:null,completedAt:new Date()}).where(and(eq(replacements.id,replacement.id),eq(replacements.status,'processing')));const event={id:`evt_${replacement.id}`,organizationId:replacement.organizationId,type:'replacement.completed',aggregateId:replacement.id,data:{replacement_id:replacement.id,source_line_id:source.id,target_line_id:target.id},requestId:replacement.requestId};await tx.insert(events).values(event).onConflictDoNothing();const hooks=await tx.select().from(webhooks).where(and(eq(webhooks.organizationId,replacement.organizationId),eq(webhooks.enabled,true)));for(const hook of hooks)await tx.insert(webhookDeliveries).values({id:`whd_${replacement.id}_${hook.id}`,eventId:event.id,webhookId:hook.id}).onConflictDoNothing();});}

async function releaseTargetIfSafe(database:Database,replacementId:string){const[order]=await database.select().from(providerOrders).where(eq(providerOrders.replacementId,replacementId)).limit(1);if(order&&['completed','unknown'].includes(order.status))return;await database.update(lines).set({status:'available',reservedByReplacementId:null,updatedAt:new Date()}).where(and(eq(lines.reservedByReplacementId,replacementId),eq(lines.status,'provisioning')));}
export async function runClaimedJob(database:Database,provider:ConnectivityProvider,job:ClaimedJob,now=new Date()){try{await executeReplacement(database,provider,job.payload.replacementId);await database.update(jobs).set({status:'completed',lockedAt:null,lockedBy:null,lastError:null}).where(and(eq(jobs.id,job.id),eq(jobs.lockedBy,job.lockedBy)));}catch(error){const message=error instanceof Error?error.message:String(error);const retryable=error instanceof ProviderError?error.retryable:error instanceof DomainError?error.retryable:true;if(retryable&&job.attempts<config.MAX_JOB_ATTEMPTS){await database.update(jobs).set({status:'pending',lockedAt:null,lockedBy:null,lastError:message,availableAt:new Date(now.getTime()+retryDelayMs(job.attempts,config.JOB_RETRY_BASE_MS))}).where(and(eq(jobs.id,job.id),eq(jobs.lockedBy,job.lockedBy)));return;}const code=error instanceof ProviderError?error.code:error instanceof DomainError?error.code:'INTERNAL_ERROR';await database.update(jobs).set({status:'failed',lockedAt:null,lockedBy:null,lastError:message}).where(and(eq(jobs.id,job.id),eq(jobs.lockedBy,job.lockedBy)));await database.update(replacements).set({status:'failed',failureCode:retryable?'MAX_RETRIES_EXHAUSTED':code}).where(and(eq(replacements.id,job.payload.replacementId),dsql`${replacements.status}<>'completed'`));await releaseTargetIfSafe(database,job.payload.replacementId);}}
export function startWorker(database:Database=defaultDb,provider:ConnectivityProvider=new SandboxProvider()){const workerId=`wrk_${randomUUID()}`;let stopped=false;const tick=async()=>{if(stopped)return;const job=await claimJob(database,workerId);if(job)await runClaimedJob(database,provider,job);};const timer=setInterval(()=>void tick(),config.WORKER_POLL_MS);void tick();return()=>{stopped=true;clearInterval(timer);};}
if(import.meta.url===pathToFileURL(process.argv[1]??'').href)startWorker();
