import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
const databaseUrl=process.env.TEST_DATABASE_URL;
const pg=databaseUrl?describe:describe.skip;

pg('V0.2.1 PostgreSQL integration',()=>{
  let db:any,sql:any,schema:any,buildApp:any,hashKey:any,claimJob:any,runClaimedJob:any,executeReplacement:any,SandboxProvider:any,ProviderError:any,encryptWebhookSecret:any,config:any;
  const keyA='lv_test_organization_a';const keyB='lv_test_organization_b';
  beforeAll(async()=>{process.env.DATABASE_URL=databaseUrl!;process.env.LINVY_BOOTSTRAP_API_KEY=keyA;process.env.WEBHOOK_MASTER_KEY=Buffer.alloc(32,7).toString('base64');process.env.JOB_LEASE_MS='100';process.env.MAX_JOB_ATTEMPTS='3';process.env.JOB_RETRY_BASE_MS='10';({db,sql}=await import('../src/db.js'));schema=await import('../src/db/schema.js');({buildApp}=await import('../src/server.js'));({hashKey}=await import('../src/auth.js'));({claimJob,runClaimedJob,executeReplacement}=await import('../src/worker.js'));({SandboxProvider,ProviderError}=await import('../src/provider.js'));({encryptWebhookSecret}=await import('../src/webhook-secret.js'));({config}=await import('../src/config.js'));});
  afterAll(async()=>{if(sql)await sql.end();});
  beforeEach(async()=>{await sql.unsafe('truncate table webhook_deliveries, events, provider_orders, jobs, idempotency_keys, replacements, incidents, assignments, lines, api_keys, people, providers, organizations restart identity cascade');await db.insert(schema.organizations).values([{id:'org_a',name:'A'},{id:'org_b',name:'B'}]);await db.insert(schema.providers).values([{id:'prv_a',organizationId:'org_a',kind:'sandbox',name:'A'},{id:'prv_b',organizationId:'org_b',kind:'sandbox',name:'B'}]);await db.insert(schema.people).values([{id:'per_a',organizationId:'org_a',name:'Alice'},{id:'per_b',organizationId:'org_b',name:'Bob'}]);await db.insert(schema.lines).values([{id:'src_a',organizationId:'org_a',providerId:'prv_a',phoneNumber:'1',region:'RJ',simType:'esim',status:'active'},{id:'src_a2',organizationId:'org_a',providerId:'prv_a',phoneNumber:'2',region:'RJ',simType:'esim',status:'active'},{id:'target_a',organizationId:'org_a',providerId:'prv_a',phoneNumber:'3',region:'RJ',simType:'esim',status:'available'},{id:'wrong_region',organizationId:'org_a',providerId:'prv_a',phoneNumber:'4',region:'SP',simType:'esim',status:'available'},{id:'src_b',organizationId:'org_b',providerId:'prv_b',phoneNumber:'5',region:'RJ',simType:'esim',status:'active'}]);await db.insert(schema.assignments).values({id:'asn_a',organizationId:'org_a',lineId:'src_a',personId:'per_a',deviceId:'dev',costCenter:'ops'});await db.insert(schema.apiKeys).values([{id:'key_a',organizationId:'org_a',prefix:'lv_test_a',keyHash:hashKey(keyA),scopes:['lines:read','incidents:write','replacements:read','replacements:write']},{id:'key_b',organizationId:'org_b',prefix:'lv_test_b',keyHash:hashKey(keyB),scopes:['lines:read','incidents:write','replacements:read','replacements:write']}]);await db.insert(schema.webhooks).values({id:'hook_a',organizationId:'org_a',url:'https://example.invalid',encryptedSecret:encryptWebhookSecret('whsec_test',config.WEBHOOK_MASTER_KEY)});});
  const headers=(key=keyA)=>({authorization:`Bearer ${key}`,'content-type':'application/json'});
  async function app(){return buildApp(db);}
  async function replacement(source='src_a',suffix='x',incident_id?:string){const application=await app();const response=await application.inject({method:'POST',url:`/v1/lines/${source}/replacements`,headers:{...headers(),'idempotency-key':`idem-${suffix}-12345`},payload:{reason:'sim_failure',...(incident_id?{incident_id}:{})}});await application.close();return response;}
  async function insertWork(repId='rep_test',source='src_a',attempts=0){await db.insert(schema.replacements).values({id:repId,organizationId:'org_a',sourceLineId:source,reason:'sim_failure',requestId:`req_${repId}`});await db.insert(schema.jobs).values({id:`job_${repId}`,organizationId:'org_a',type:'replacement.execute',payload:{replacementId:repId},attempts});}

  it('rejects incident creation on another tenant line',async()=>{const a=await app();const r=await a.inject({method:'POST',url:'/v1/incidents',headers:headers(),payload:{line_id:'src_b',reason:'failure'}});expect(r.statusCode).toBe(404);await a.close();});
  it('rejects replacement creation on another tenant line',async()=>{const r=await replacement('src_b','cross');expect(r.statusCode).toBe(404);});
  it('rejects cross-tenant incident association',async()=>{await db.insert(schema.incidents).values({id:'inc_b',organizationId:'org_b',lineId:'src_b',reason:'x'});const r=await replacement('src_a','inc-cross','inc_b');expect(r.statusCode).toBe(404);});
  it('hides cross-tenant replacement lookup',async()=>{await db.insert(schema.replacements).values({id:'rep_b',organizationId:'org_b',sourceLineId:'src_b',reason:'sim_failure',requestId:'req'});const a=await app();const r=await a.inject({method:'GET',url:'/v1/replacements/rep_b',headers:headers()});expect(r.statusCode).toBe(404);await a.close();});
  it('returns same response for same idempotency key and payload',async()=>{const one=await replacement('src_a','same');const two=await replacement('src_a','same');expect(two.statusCode).toBe(202);expect(two.json().id).toBe(one.json().id);});
  it('returns 409 when idempotency key payload changes',async()=>{await replacement('src_a','diff');const a=await app();const r=await a.inject({method:'POST',url:'/v1/lines/src_a/replacements',headers:{...headers(),'idempotency-key':'idem-diff-12345'},payload:{reason:'device_change'}});expect(r.statusCode).toBe(409);await a.close();});
  it('blocks fraud before persistence',async()=>{const a=await app();const r=await a.inject({method:'POST',url:'/v1/lines/src_a/replacements',headers:{...headers(),'idempotency-key':'fraud-key-123'},payload:{reason:'fraud'}});expect(r.statusCode).toBe(409);expect(r.json().error.code).toBe('RISK_REVIEW_REQUIRED');await a.close();});
  it('atomically prevents two replacements reserving one target',async()=>{await insertWork('rep_1','src_a');await insertWork('rep_2','src_a2');const results=await Promise.allSettled([executeReplacement(db,new SandboxProvider(),'rep_1'),executeReplacement(db,new SandboxProvider(),'rep_2')]);expect(results.filter((x:any)=>x.status==='fulfilled')).toHaveLength(1);const rows=await db.select().from(schema.replacements);expect(rows.filter((x:any)=>x.status==='completed')).toHaveLength(1);expect(new Set(rows.map((x:any)=>x.targetLineId).filter(Boolean)).size).toBe(1);});
  it('moves target available to provisioning to active and source to replaced',async()=>{await insertWork();let observed='';const provider={activate:async(command:any)=>{const[target]=await db.select().from(schema.lines).where((await import('drizzle-orm')).eq(schema.lines.id,command.resourceId));observed=target.status;return{status:'completed',reference:'ok'};},getStatus:async()=> 'active'};await executeReplacement(db,provider,'rep_test');const rows=await db.select().from(schema.lines);expect(observed).toBe('provisioning');expect(rows.find((x:any)=>x.id==='target_a').status).toBe('active');expect(rows.find((x:any)=>x.id==='src_a').status).toBe('replaced');});
  it('transfers assignment exactly once and completes exactly once',async()=>{await insertWork();await executeReplacement(db,new SandboxProvider(),'rep_test');await executeReplacement(db,new SandboxProvider(),'rep_test');const active=await sql.unsafe("select * from assignments where ended_at is null");expect(active).toHaveLength(1);expect(active[0].line_id).toBe('target_a');const[rep]=await db.select().from(schema.replacements);expect(rep.status).toBe('completed');});
  it('fails terminally with NO_ELIGIBLE_RESOURCE',async()=>{await db.update(schema.lines).set({status:'terminated'}).where((await import('drizzle-orm')).eq(schema.lines.id,'target_a'));await insertWork();const job=await claimJob(db,'worker');await runClaimedJob(db,new SandboxProvider(),job);const[rep]=await db.select().from(schema.replacements);expect(rep.failureCode).toBe('NO_ELIGIBLE_RESOURCE');});
  it('schedules retryable provider failure with backoff',async()=>{await insertWork();const job=await claimJob(db,'worker');await runClaimedJob(db,new SandboxProvider('temporary_failure'),job,new Date(0));const[row]=await db.select().from(schema.jobs);expect(row.status).toBe('pending');expect(row.attempts).toBe(1);expect(row.availableAt.getTime()).toBeGreaterThan(0);});
  it('releases a safely reserved target on terminal provider failure',async()=>{await insertWork();const job=await claimJob(db,'worker');await runClaimedJob(db,new SandboxProvider('terminal_failure'),job);const[target]=await db.select().from(schema.lines).where((await import('drizzle-orm')).eq(schema.lines.id,'target_a'));const[rep]=await db.select().from(schema.replacements);expect(rep.failureCode).toBe('PROVISIONING_FAILED');expect(target.status).toBe('available');});
  it('recovers stale leases but not valid leases',async()=>{await insertWork();await db.update(schema.jobs).set({status:'processing',lockedAt:new Date(0),lockedBy:'dead'});expect(await claimJob(db,'new',new Date())).toBeTruthy();await db.update(schema.jobs).set({status:'processing',lockedAt:new Date(),lockedBy:'live'});expect(await claimJob(db,'other',new Date())).toBeUndefined();});
  it('marks replacement failed after max retry exhaustion',async()=>{await insertWork('rep_max','src_a',2);const job=await claimJob(db,'worker',new Date(Date.now()+1000));await runClaimedJob(db,new SandboxProvider('temporary_failure'),job);const[rep]=await db.select().from(schema.replacements);expect(rep.failureCode).toBe('MAX_RETRIES_EXHAUSTED');});
  it('uses one stable provider operation key',async()=>{await insertWork();await executeReplacement(db,new SandboxProvider(),'rep_test');await executeReplacement(db,new SandboxProvider(),'rep_test');const orders=await db.select().from(schema.providerOrders);expect(orders).toHaveLength(1);expect(orders[0].operationKey).toBe('prv_a:activate:rep_test');});
  it('creates event and webhook outbox only once',async()=>{await insertWork();await executeReplacement(db,new SandboxProvider(),'rep_test');await executeReplacement(db,new SandboxProvider(),'rep_test');expect(await db.select().from(schema.events)).toHaveLength(1);expect(await db.select().from(schema.webhookDeliveries)).toHaveLength(1);});
  it('completes incident to replacement to worker end to end',async()=>{const a=await app();const incidentResponse=await a.inject({method:'POST',url:'/v1/incidents',headers:headers(),payload:{line_id:'src_a',reason:'sim failure'}});expect(incidentResponse.statusCode).toBe(201);const incidentId=incidentResponse.json().id;const replacementResponse=await a.inject({method:'POST',url:'/v1/lines/src_a/replacements',headers:{...headers(),'idempotency-key':'e2e-flow-12345'},payload:{reason:'sim_failure',incident_id:incidentId}});expect(replacementResponse.statusCode).toBe(202);const job=await claimJob(db,'e2e-worker');await runClaimedJob(db,new SandboxProvider(),job);const statusResponse=await a.inject({method:'GET',url:`/v1/replacements/${replacementResponse.json().id}`,headers:headers()});expect(statusResponse.json().status).toBe('completed');const[incident]=await db.select().from(schema.incidents);expect(incident.status).toBe('resolved');await a.close();});
  it('keeps target reserved when provider outcome is unknown',async()=>{await insertWork();const job=await claimJob(db,'worker');await runClaimedJob(db,new SandboxProvider('unknown'),job);const[target]=await db.select().from(schema.lines).where((await import('drizzle-orm')).eq(schema.lines.id,'target_a'));const[order]=await db.select().from(schema.providerOrders);expect(order.status).toBe('unknown');expect(target.status).toBe('provisioning');});
});
