import {afterAll,beforeAll,beforeEach,describe,expect,it} from 'vitest';
const databaseUrl=process.env.TEST_DATABASE_URL;const pg=databaseUrl?describe:describe.skip;
pg('V0.2.2 webhook PostgreSQL integration',()=>{
  let db:any,sql:any,s:any,claim:any,dispatch:any,claimJob:any,runJob:any,SandboxProvider:any,encrypt:any,decrypt:any,buildApp:any,hashKey:any,masterKey:Buffer;
  beforeAll(async()=>{process.env.DATABASE_URL=databaseUrl!;process.env.LINVY_BOOTSTRAP_API_KEY='lv_test_webhook_key';process.env.WEBHOOK_MASTER_KEY=Buffer.alloc(32,7).toString('base64');({db,sql}=await import('../src/db.js'));s=await import('../src/db/schema.js');({claimWebhookDelivery:claim,dispatchClaimedDelivery:dispatch}=await import('../src/webhook-worker.js'));({claimJob,runClaimedJob:runJob}=await import('../src/worker.js'));({SandboxProvider}=await import('../src/provider.js'));({encryptWebhookSecret:encrypt,decryptWebhookSecret:decrypt}=await import('../src/webhook-secret.js'));({buildApp}=await import('../src/server.js'));({hashKey}=await import('../src/auth.js'));masterKey=Buffer.alloc(32,7);});
  afterAll(async()=>{if(sql)await sql.end();});
  beforeEach(async()=>{await sql.unsafe('truncate table webhook_deliveries, events, webhooks, api_keys, organizations restart identity cascade');await db.insert(s.organizations).values([{id:'org_a',name:'A'},{id:'org_b',name:'B'}]);await db.insert(s.apiKeys).values([{id:'ka',organizationId:'org_a',prefix:'a',keyHash:hashKey('lv_test_webhook_key'),scopes:['webhooks:read','webhooks:write','incidents:write','replacements:write','replacements:read']},{id:'kb',organizationId:'org_b',prefix:'b',keyHash:hashKey('lv_test_webhook_other'),scopes:['webhooks:read','webhooks:write']}]);});
  async function setup(overrides:any={}){await db.insert(s.webhooks).values({id:'whk_a',organizationId:'org_a',url:'https://hook.example',encryptedSecret:encrypt('whsec_known',masterKey),...overrides});await db.insert(s.events).values({id:'evt_a',organizationId:'org_a',type:'replacement.completed',aggregateId:'rep_a',data:{z:2,a:1},requestId:'req_a'});await db.insert(s.webhookDeliveries).values({id:'whd_a',eventId:'evt_a',webhookId:'whk_a'});return claim(db,'worker',new Date(),100);}
  const result=(status:number,retryAfter?:string)=>({post:async()=>({status,retryAfter,durationMs:3})});
  it('delivers 2xx once with verifiable canonical signature',async()=>{const job=await setup();let sent:any;await dispatch(db,{post:async(url:string,body:string,headers:any)=>{sent={url,body,headers};return{status:204,durationMs:2};}},job,{masterKey});const[row]=await db.select().from(s.webhookDeliveries);expect(row.status).toBe('delivered');expect(row.deliveredAt).toBeTruthy();expect(sent.body).toContain('"created_at"');const {signWebhook}=await import('../src/webhook-worker.js');expect(sent.headers['Linvy-Signature']).toBe(signWebhook('whsec_known',sent.headers['Linvy-Timestamp'],sent.body));expect(await claim(db,'other')).toBeUndefined();});
  it('retries 500 and 429 without duplicating outbox',async()=>{let job=await setup();await dispatch(db,result(500),job,{masterKey,retryBaseMs:1});await db.update(s.webhookDeliveries).set({nextAttemptAt:new Date(0)});job=await claim(db,'second');await dispatch(db,result(200),job,{masterKey});const rows=await db.select().from(s.webhookDeliveries);expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({status:'delivered',attempts:2,responseStatus:200});});
  it('reschedules 429 and honors bounded Retry-After',async()=>{const now=new Date();const job=await setup();await dispatch(db,result(429,'120'),job,{masterKey,retryMaxMs:5000},now);const[row]=await db.select().from(s.webhookDeliveries);expect(row.status).toBe('pending');expect(row.nextAttemptAt.getTime()-now.getTime()).toBe(5000);});
  it('marks 400 and redirect terminal',async()=>{let job=await setup();await dispatch(db,result(400),job,{masterKey});let[row]=await db.select().from(s.webhookDeliveries);expect(row.status).toBe('failed');await sql.unsafe('truncate table webhook_deliveries, events, webhooks cascade');job=await setup();await dispatch(db,result(302),job,{masterKey});[row]=await db.select().from(s.webhookDeliveries);expect(row.status).toBe('failed');});
  it('retries timeout and fails after maximum attempts',async()=>{const job=await setup();const error=Object.assign(new Error('timeout'),{retryable:true});await dispatch(db,{post:async()=>{throw error;}},job,{masterKey,maxAttempts:1});const[row]=await db.select().from(s.webhookDeliveries);expect(row.status).toBe('failed');expect(row.attempts).toBe(1);});
  it('recovers expired lease but never steals a valid lease',async()=>{await setup();await db.update(s.webhookDeliveries).set({status:'processing',lockedAt:new Date(0),lockedBy:'dead'});expect(await claim(db,'recovery',new Date(),100)).toBeTruthy();await db.update(s.webhookDeliveries).set({status:'processing',lockedAt:new Date(),lockedBy:'live'});expect(await claim(db,'thief',new Date(),100)).toBeUndefined();});
  it('allows only one concurrent dispatcher claim',async()=>{await setup();await db.update(s.webhookDeliveries).set({status:'pending',lockedAt:null,lockedBy:null,attempts:0});const claims=await Promise.all([claim(db,'one'),claim(db,'two')]);expect(claims.filter(Boolean)).toHaveLength(1);});
  it('does not send a disabled webhook',async()=>{const job=await setup({enabled:false});let calls=0;await dispatch(db,{post:async()=>{calls++;return{status:200,durationMs:1};}},job,{masterKey});const[row]=await db.select().from(s.webhookDeliveries);expect(calls).toBe(0);expect(row.status).toBe('failed');});
  it('fails terminally when encrypted secret cannot be recovered',async()=>{const job=await setup({encryptedSecret:encrypt('secret',Buffer.alloc(32,3))});await dispatch(db,result(200),job,{masterKey});const[row]=await db.select().from(s.webhookDeliveries);expect(row.status).toBe('failed');});
  it('creates secret once, never lists it, and isolates tenants',async()=>{const app=await buildApp(db);const auth={authorization:'Bearer lv_test_webhook_key'};const created=await app.inject({method:'POST',url:'/v1/webhooks',headers:auth,payload:{url:'https://client.example/hook'}});expect(created.statusCode).toBe(201);expect(created.json().secret).toMatch(/^whsec_/);const listed=await app.inject({method:'GET',url:'/v1/webhooks',headers:auth});expect(JSON.stringify(listed.json())).not.toContain('secret');const cross=await app.inject({method:'DELETE',url:'/v1/webhooks/'+created.json().id,headers:{authorization:'Bearer lv_test_webhook_other'}});expect(cross.statusCode).toBe(404);const[stored]=await db.select().from(s.webhooks).where((await import('drizzle-orm')).eq(s.webhooks.id,created.json().id));expect(stored.encryptedSecret).not.toContain(created.json().secret);expect(decrypt(stored.encryptedSecret,masterKey)).toBe(created.json().secret);await app.close();});
  it('runs incident through replacement and signed HTTP delivery end to end',async()=>{await db.insert(s.providers).values({id:'prv',organizationId:'org_a',kind:'sandbox',name:'Sandbox'});await db.insert(s.people).values({id:'per',organizationId:'org_a',name:'Person'});await db.insert(s.lines).values([{id:'src',organizationId:'org_a',providerId:'prv',phoneNumber:'1',region:'RJ',simType:'esim',status:'active'},{id:'target',organizationId:'org_a',providerId:'prv',phoneNumber:'2',region:'RJ',simType:'esim',status:'available'}]);await db.insert(s.assignments).values({id:'asn',organizationId:'org_a',lineId:'src',personId:'per'});const app=await buildApp(db);const headers={authorization:'Bearer lv_test_webhook_key'};const hook=await app.inject({method:'POST',url:'/v1/webhooks',headers,payload:{url:'https://endpoint.example'}});const incident=await app.inject({method:'POST',url:'/v1/incidents',headers,payload:{line_id:'src',reason:'failure'}});const replacement=await app.inject({method:'POST',url:'/v1/lines/src/replacements',headers:{...headers,'idempotency-key':'webhook-e2e-key'},payload:{reason:'sim_failure',incident_id:incident.json().id}});const job=await claimJob(db,'replacement-worker');await runJob(db,new SandboxProvider(),job);const delivery=await claim(db,'webhook-worker');let sent:any;await dispatch(db,{post:async(_url:string,body:string,outboundHeaders:any)=>{sent={body,headers:outboundHeaders};return{status:200,durationMs:1};}},delivery,{masterKey});const[row]=await db.select().from(s.webhookDeliveries);const {signWebhook}=await import('../src/webhook-signing.js');expect(replacement.statusCode).toBe(202);expect(sent.body).toContain(replacement.json().id);expect(sent.headers['Linvy-Signature']).toBe(signWebhook(hook.json().secret,sent.headers['Linvy-Timestamp'],sent.body));expect(row.status).toBe('delivered');await app.close();});
});
